### ISSUE TITLE
Dies on 503 error

### ISSUE THREAD

**Issue by cystic** [cystic/IOTA-Faucet-Bot#6]
Traceback (most recent call last):
  File "if.py", line 28, in <module>
    for submission in subreddit.stream.submissions():
  File "/Library/Python/2.7/site-packages/praw/models/util.py", line 156, in stream_generator
    limit=limit, params={'before': before_fullname}))):
  File "/Library/Python/2.7/site-packages/praw/models/listing/generator.py", line 79, in next
    return self.__next__()
  File "/Library/Python/2.7/site-packages/praw/models/listing/generator.py", line 52, in __next__
    self._next_batch()
  File "/Library/Python/2.7/site-packages/praw/models/listing/generator.py", line 62, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "/Library/Python/2.7/site-packages/praw/reddit.py", line 367, in get
    data = self.request('GET', path, params=params)
  File "/Library/Python/2.7/site-packages/praw/reddit.py", line 472, in request
    params=params)
  File "/Library/Python/2.7/site-packages/prawcore/sessions.py", line 175, in request
    params=params, url=url)
  File "/Library/Python/2.7/site-packages/prawcore/sessions.py", line 121, in _request_with_retries
    retries, saved_exception, url)
  File "/Library/Python/2.7/site-packages/prawcore/sessions.py", line 87, in _do_retry
    params=params, url=url, retries=retries - 1)
  File "/Library/Python/2.7/site-packages/prawcore/sessions.py", line 121, in _request_with_retries
    retries, saved_exception, url)
  File "/Library/Python/2.7/site-packages/prawcore/sessions.py", line 87, in _do_retry
    params=params, url=url, retries=retries - 1)
  File "/Library/Python/2.7/site-packages/prawcore/sessions.py", line 123, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.ServerError: received 503 HTTP response

**Comment by cystic** [comment]
The bot dies when it times out due to the reddit server or my internet lagging. I need the bot to stay running, resetting it a couple times a week is getting old. Any help is much appreciated!
